---

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./resources/sealedSecret.yaml


configurations:
  - ./configurations/nameReference.yaml


transformers:
  - ./transformers/annotation.yaml
