---

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generators:
  - ../../../base/secret/generator/patches/disableNameSuffixHash/true


resources:
  - ../../../base/sealedSecret


transformers:
  - ../../../base/secret/annotation/sealedsecrets
