---

apiVersion: builtin
kind: AnnotationsTransformer
metadata:
  name: secret

annotations:
  sealedsecrets.bitnami.com/managed: "true"
  sealedsecrets.bitnami.com/namespace-wide: "true"

fieldSpecs:
  - kind: Secret
    path: metadata/annotations
    create: true
