---

apiVersion: builtin
kind: AnnotationsTransformer
metadata:
  name: secretArgoCD

annotations:
  argocd.argoproj.io/hook: Skip

fieldSpecs:
  - kind: Secret
    path: metadata/annotations
    create: true

---

apiVersion: builtin
kind: AnnotationsTransformer
metadata:
  name: sealedSecretArgoCD

annotations:
  # argocd.argoproj.io/hook: PreSync
  argocd.argoproj.io/sync-wave: "-1"

fieldSpecs:
  - kind: SealedSecret
    path: metadata/annotations
    create: true

---

apiVersion: builtin
kind: AnnotationsTransformer
metadata:
  name: sealedSecretTemplateArgoCD

annotations:
  argocd.argoproj.io/hook: Skip

fieldSpecs:
  - kind: SealedSecret
    path: spec/template/metadata/annotations
    create: true