---

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sealed-secret
  labels: {}
  annotations: {}

spec:
  encryptedData: {}

  template:
    metadata:
      labels: {}
      annotations: {}
    
    type: Opaque
